MODEL:
    framework: "ActBert"
    backbone:
        name: "BertForMultiModalPreTraining"


DATASET: #DATASET field
    num_workers: 4
    test_batch_size: 1
    test:
        format: "MSRVTTDataset"
        file_path: "/workspace/huangjun12/PaddleProject/ActBert/main/test_data/MSRVTT_JSFUSION_test.csv"
        features_path: "/workspace/huangjun12/PaddleProject/ActBert/main/test_data/msrvtt_test.lmdb"

PIPELINE: #PIPELINE field
    test:


METRIC:
    name: 'MSRVTTMetric'


model_name: "ActBert"
